const first_impression = [
  "almost matured", 
  "austere", 
  "big and strong", 
  "cedary", 
  "chewy", 
  "chunky", 
  "clean", 
  "corpulent", 
  "creepy", 
  "crisp", 
  "dark and mysterious", 
  "desperate", 
  "egocentric", 
  "elegant", 
  "evenly proportioned", 
  "evil", 
  "fancy", 
  "firm and textured", 
  "finely balanced", 
  "flourished", 
  "frank", 
  "fully refined", 
  "fun", 
  "generous", 
  "glassy", 
  "good", 
  "grossly overweight", 
  "historic", 
  "hopped-up", 
  "impressive", 
  "intelligently done", 
  "intense", 
  "juicy", 
  "lean", 
  "light and simple", 
  "markedly improved", 
  "meaty", 
  "modern", 
  "modest", 
  "nearly matured", 
  "neo-classic", 
  "overaged", 
  "overbearing", 
  "overdone", 
  "overdressed", 
  "powerful", 
  "premature", 
  "pretty", 
  "raw", 
  "ready to drink", 
  "remarkable", 
  "rich and smokey", 
  "rich and thick", 
  "rude", 
  "rustic", 
  "serious", 
  "soft", 
  "sturdy", 
  "tightly wound", 
  "tightly woven", 
  "twisted", 
  "unimpressive", 
  "unnatural", 
  "unrefined", 
  "well focused", 
  "wholly obtuse", 
  "wicked", 
  "wimpy"
];

const conjunction = [
  "almost", 
  "and", 
  "but", 
  "yet"
];

const adjective = [
  "acidic", 
  "aggressive", 
  "arcane", 
  "astounding", 
  "attractive", 
  "big and plump", 
  "boggling", 
  "brackish", 
  "broad-shouldered", 
  "complex and stunning", 
  "corpulent", 
  "desperate", 
  "elegant", 
  "extra ripe", 
  "fat", 
  "fleshy", 
  "focused", 
  "freakishly evil", 
  "french-oaked", 
  "graceful", 
  "hedonistic", 
  "hopeless", 
  "hoppy", 
  "intense", 
  "lacking in character", 
  "lackluster", 
  "limp", 
  "longingly elegant", 
  "meandering", 
  "melancholy", 
  "middle-aged", 
  "morally superior", 
  "musty", 
  "oaky", 
  "overly American", 
  "oily", 
  "open-ended", 
  "over-the-top", 
  "overcooked", 
  "overdone", 
  "plump", 
  "putrid", 
  "ripe", 
  "sad", 
  "sassy", 
  "second-rate", 
  "smoked", 
  "soggy", 
  "structured", 
  "sturdy", 
  "sugary", 
  "supple", 
  "sweet", 
  "underdone", 
  "understated", 
  "unripe", 
  "whimsical", 
  "wicked", 
  "yellowed", 
  "zealous"
];

const leadin = [
  "a mouthful of", 
  "aromas of", 
  "attacks with", 
  "begins with", 
  "bites you with", 
  "detecable notes of", 
  "displays", 
  "essenses of", 
  "hints of", 
  "kicks you with", 
  "opens with", 
  "reminds one of", 
  "reminiscent of", 
  "resembles", 
  "spews", 
  "starts with", 
  "strong", 
  "the curtain opens with",
  "whispers of"
];

const flavor = [
  "american oak", 
  "anise", 
  "apple", 
  "banana", 
  "barley", 
  "beef", 
  "bing cherry", 
  "black cherry", 
  "blackberry", 
  "blueberry", 
  "bourbon", 
  "buttered scones", 
  "caramel", 
  "cardboard", 
  "carrots", 
  "cedar", 
  "celery", 
  "chutney", 
  "cigar box", 
  "clay", 
  "cocoa", 
  "coffee", 
  "currant", 
  "dirt", 
  "earth", 
  "fig", 
  "foie gras", 
  "fragrant citrus", 
  "french oak", 
  "fruit punch", 
  "garlic", 
  "ginger", 
  "green tea", 
  "herbs", 
  "honey", 
  "juniper", 
  "kalamata olive", 
  "lemon", 
  "licorice", 
  "lime", 
  "loganberry", 
  "mango", 
  "maple syrup", 
  "marmalade", 
  "melon", 
  "mint", 
  "mint julip", 
  "mocha", 
  "nectarine", 
  "onion", 
  "orange peel", 
  "papaya", 
  "peach", 
  "peach pits", 
  "pear", 
  "pepper", 
  "pineapple", 
  "plum", 
  "prune", 
  "prune juice", 
  "raisin", 
  "raspberry", 
  "roasted pork", 
  "roasted vegetables", 
  "rye", 
  "sage", 
  "salad", 
  "salt", 
  "salted beef", 
  "seedless watermelon", 
  "shallots", 
  "smoked bacon", 
  "spice", 
  "spruce", 
  "strawberry jam", 
  "sun-dried tomato", 
  "tangerine", 
  "tea notes", 
  "thyme", 
  "toast", 
  "toasty oak", 
  "tobacco", 
  "tomato", 
  "vanilla", 
  "wet raisins", 
  "wild berry", 
  "yew bark"
];

const qualifier = [
  "a modicum of", 
  "aggressive", 
  "bashful", 
  "corpulent", 
  "dainty", 
  "forceful", 
  "forward", 
  "hints of", 
  "hopeful", 
  "light", 
  "lingering", 
  "perceptible", 
  "scant", 
  "strong", 
  "strong-willed", 
  "total absence of", 
  "traces of", 
  "weak"
];

const when_start = [
  "now",
  "now",
  "tomorrow morning", 
  "yesterday",
];

const when_end = [
  "2020",
  "2032",
  "April",
  "August 5th",
  "Christmas",
  "Friday",
  "Groundhog Day",
  "Halloween",
  "President's Day",
  "graduation", 
  "never",
  "next payday", 
  "second Tuesday of the month",
  "seventh Saturday of next year",
];

export {
  first_impression,
  conjunction,
  adjective,
  leadin,
  flavor,
  qualifier,
  when_start,
  when_end
};
