export const firstImpression = [
  'Oprah-esque',
  'Beyonce-esque',
  'Meg Ryan in a glass',
  'a Shakespearean dream child',
  'a little needy',
  'a ruby rich delight',
  'a true virtuoso',
  'a wine for the brutish and senile',
  'almost matured',
  'austere',
  'beautifully aged',
  'big and strong',
  'bold yet creamy',
  'cedary',
  'chewy',
  'chunky',
  'clean',
  'corpulent',
  'creepy',
  'crisp',
  'dark and mysterious',
  'dark as a David Fincher movie',
  'desperate',
  'disappointingly jaunty',
  'earthly wooded forest floor',
  'edgy',
  'egocentric',
  'elegant',
  'erotically scented',
  'evenly proportioned',
  'evil',
  'extravagantly soft',
  'fancy',
  'finely balanced',
  'firm and textured',
  'flourished',
  'frank',
  'fully refined',
  'fun',
  'generous',
  'glassy',
  'good',
  'grossly overweight',
  'historic',
  'hopped-up',
  'impressive',
  'intelligently done',
  'intense',
  'juicy',
  'kind of full of itself',
  'lacking in character',
  'lean',
  'levity uncommon for its vintage',
  'light and simple',
  'lightly hot',
  'markedly improved',
  'meaty',
  'modern',
  'modest',
  'nearly matured',
  'neo-classic',
  'overaged',
  'overbearing',
  'overdone',
  'overdressed',
  'powerful',
  'precocious and pretentious',
  'premature',
  'pretty',
  'raw',
  'ready to drink',
  'remarkable',
  'rich and smokey',
  'rich and thick',
  'rude',
  'rustic',
  'seemingly schistic',
  'serious',
  'soft',
  'sturdy',
  'terrific tenacity',
  'tightly wound',
  'tightly woven',
  'twisted',
  'unimpressive',
  'unnatural',
  'unrefined',
  'utterly mundane',
  'well balanced',
  'well focused',
  'wholly obtuse',
  'wicked',
  'wimpy'
]

export const conjunction = [
  'almost',
  'although somehow',
  'and',
  'and',
  'but',
  'yet'
]

export const adjective = [
  'acidic',
  'aggressive',
  'arcane',
  'astounding',
  'attractive',
  'blooming',
  'boggling',
  'brackish',
  'broad-shouldered',
  'celestial',
  'corpulent',
  'deeply scented',
  'desperate',
  'devilish',
  'elegant',
  'exotic',
  'extra ripe',
  'flamboyant',
  'fleshy',
  'focused',
  'freakishly evil',
  'french-oaked',
  'graceful',
  'grandiose',
  'harmonious',
  'hedonistic',
  'hopeless',
  'hoppy',
  'intense',
  'lackluster',
  'limp',
  'longingly elegant',
  'meandering',
  'melancholy',
  'middle-aged',
  'morally superior',
  'mouth-watering',
  'musty',
  'oaky',
  'oily',
  'open-ended',
  'over-the-top',
  'overcooked',
  'overdone',
  'overly American',
  'overzealous',
  'plump',
  'provocative',
  'putrid',
  'ripe',
  'sad',
  'sassy',
  'savory',
  'second-rate',
  'smoked',
  'soggy',
  'structured',
  'sturdy',
  'sugary',
  'sumptuous',
  'supple',
  'sweet',
  'underdone',
  'understated',
  'unripe',
  'whimsical',
  'wicked',
  'yellowed'
]

export const leadin = [
  'a brooding mistress of',
  'a generous dose of',
  'a mouthful of',
  'a nose of',
  'a tactile sense of',
  'aromas of',
  'attacks with',
  'begins with',
  'bites you with',
  'detecable notes of',
  'displays',
  'endowed with',
  'essenses of',
  'every sip brings reminisces of',
  'hints of',
  'kicks you with',
  'opens with',
  'packed with',
  'reminds one of',
  'reminiscent of',
  'resembles',
  'resinous evocations of',
  'spews',
  'starts with',
  'strong',
  'the curtain opens with',
  'the palate is overcome by',
  'this beauty unwinds waves of',
  'wafts of',
  'whispers of'
]

export const flavor = [
  'Frankenberry flourishes',
  'american oak',
  'anise',
  'apple',
  'asparagus',
  'balsamic odors',
  'banana',
  'barley',
  'beef',
  'bing cherry',
  'black cherry',
  'black roses',
  'blackberry',
  'blueberry',
  'bourbon',
  'boysenberry',
  'bramble',
  'buttered scones',
  'cacti',
  'caramel',
  'cardboard',
  'carrots',
  'cedar',
  'celery',
  'chutney',
  'cigar box',
  'cinnamon sticks',
  'clay',
  'cocoa',
  'coffee',
  'currant',
  'deck shoes',
  'dirt',
  'earth',
  'fair-trade dark chocolate',
  'fig',
  'foie gras',
  'fragrant citrus',
  'french oak',
  'fruit punch',
  'garlic',
  'ginger',
  'gooseberries',
  'green tea',
  'herbs',
  'honey',
  'hovercraft oil',
  'juniper',
  'kalamata olive',
  'lemon',
  'licorice',
  'lime',
  'loganberry',
  'mango',
  'maple syrup',
  'marmalade',
  'melon',
  'mint',
  'mint julip',
  'mocha',
  'nectarine',
  'onion',
  'orange peel',
  'papaya',
  'peach',
  'peach pits',
  'pear',
  'pencil shavings',
  'pepper',
  'pineapple',
  'plum',
  'prune',
  'prune juice',
  'raisin',
  'raspberry',
  'roasted pork',
  'roasted vegetables',
  'rye',
  'sage',
  'salad',
  'salt',
  'salted beef',
  'seedless watermelon',
  'shallots',
  'smoked bacon',
  'spice',
  'spruce',
  'strawberry jam',
  'sun-dried tomato',
  'tangerine',
  'tea notes',
  'thyme',
  'toast',
  'toasty oak',
  'tobacco',
  'tomato',
  'tulips',
  'vanilla',
  'wet raisins',
  'wild berry',
  'yew bark'
]

export const qualifier = [
  'a modicum of',
  'aggressive',
  'bashful',
  'corpulent',
  'dainty',
  'forceful',
  'forward',
  'hints of',
  'hopeful',
  'light',
  'lingering',
  'perceptible',
  'scant',
  'strong',
  'strong-willed',
  'total absence of',
  'traces of',
  'weak'
]

export const whenStart = [
  'now',
  'now',
  'now',
  'now',
  'in three days',
  'in 10 minutes',
  'last fortnight',
  'tomorrow afternoon',
  'yesterday'
]

export const whenEnd = [
  '8:30 PM',
  '2020',
  '2032',
  'April',
  'August 5th',
  'Christmas',
  'Friday',
  'Groundhog Day',
  'Halloween',
  "President's Day",
  'at least a decade',
  'graduation',
  'never',
  'next payday',
  'next full moon',
  'second Tuesday of the month',
  'seventh Saturday of next year',
  'the afterlife'
]
